apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-tjir
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-tjir
    app.kubernetes.io/part-of: jvm-build-suite-application-jwmi
  name: jvm-build-suite-component-tjir
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-tjir
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-tjir
    spec:
      containers:
      - image: quay.io/hugares/jvm-build-omkc-tenant/jvm-build-suite-application-jwmi/jvm-build-suite-component-tjir@sha256:80d7719eab770810b76310a3053b83d3431c32a95a2bca57186d4c16706d091b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
